### ISSUE TITLE
Why does not work?

### ISSUE THREAD

**Issue by cherneckiy** [chrishurlburt/vue-scrollview#4]
```
<Scroll-View tag="div">
  <template scope="inView">
                      <PostsBox
                                v-for="(item , index) in this.arrayPost"
                                :key="item.id"
                                :id="item.id"
                                :index="index"
                                :visible="inView.item.id"
                        ></PostsBox>
  </template>
</Scroll-View>
```

**Comment by chrishurlburt** [comment]
is ```arrayPost``` being populated asynchronously? If so, the issue is that the ```<Scroll-view>``` component is unable to detect when it's scopedSlot content changes. This is a caveat of slots in Vue.js.

In order for ```<Scroll-view>``` to begin tracking components rendered based on asynchronous data, you must call ```$scrollview.refresh()``` upon completion of your async operation.

Please see [this issue](https://github.com/chrishurlburt/vue-scrollview/issues/1) and [the docs](https://github.com/chrishurlburt/vue-scrollview#refresh) for ```.refresh```.

As an alternative to explicitly calling ```.refresh()```, you can try adding a 'key' prop to the ```<Scroll-view>``` component itself and changing the key of the ```<Scroll-view>``` anytime there's a data change. This will cause the old component instance to be thrown out and fresh one to be created.
