### ISSUE TITLE
Possible bug in IE11 and Nuxt.js

### ISSUE THREAD

**Issue by michaelpumo** [chrishurlburt/vue-scrollview#5]
Is it possible to use this with SSR with Nuxt.js?

When I check the source code, I see the literal tag in the source:

`<Scroll-View offset="100" tag="div" data-v-b22faea4 data-v-64ea40b6></Scroll-View>`

In Chrome (MacOS) the JS works fine with this, but in IE11 Windows, it takes issue with this.

**Comment by chrishurlburt** [comment]
Hi, thanks for taking the time to bring this up!

I've actually done 0 testing as far as SSR goes, so it's not really supported. However, I'm totally open to getting that up and running.

Could you give me a bit more detail about your use case and what you're looking to accomplish?

**Comment by chrishurlburt** [comment]
can confirm vue-scrollview is compatible with nuxt, however must be configured as a client-side only plugin in nuxt.config.js. SSR is not supported because scrollview directly relies on browser globals.

see: [https://nuxtjs.org/guide/plugins#client-side-only](https://nuxtjs.org/guide/plugins#client-side-only)

**Comment by chrishurlburt** [comment]
My mistake. Turns out configuring scrollview as client-side only does not work because any slotted components will not be rendered. Client-side hydration will fail resulting in a full re-render.

Will be pushing up a fix soon.

**Comment by chrishurlburt** [comment]
SSR support added in 2.2.0
