### ISSUE TITLE
[Feature Request] Add delay prop

### ISSUE THREAD

**Issue by ghost** [chrishurlburt/vue-scrollview#6]
Love the library!

I think a very good feature to have would be a delay prop as well. Often when we want to animate items in viewport we add delays for items. Easy feature to implement too, and would be a great addition to the library.

**Comment by chrishurlburt** [comment]
Hi, thanks for the kind words! I'm glad scrollview could be useful to you.

As for the delay prop, i think that would be best left to the animation library being used for your animations -- most have a delay option that can be added to tweens. css transitions/animations can also can accommodate a delay. As a last resort, you could even leverage setTimeout.

I think since there's so many options for animation delays already implemented, it doesn't make sense to duplicate that functionality here.

Thank you again for your interest and taking the time to post this suggestion!
